# Generated by Django 2.2.4 on 2019-09-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
